  - name: Start role
    debug:
      msg: "########### INSTALL TERRAFORM IN DOCKER WITH ESXI PROVIDER ###########"

  - name: Terraform - Create project dir
    file:
      path: "{{docker_projects_dir}}/terraform"
      state: directory

  - name: Terraform - Extract tar to project
    unarchive:
      src: "main.tar.gz"
      dest: "{{docker_projects_dir}}/terraform"

  - name: Terraform - Init
    shell: |
      docker run --rm -v {{docker_projects_dir}}/terraform:/project -w /project/main hashicorp/terraform:0.12.21 init
    register: output

  - debug:
      var: output.stderr_lines
      #var: output
