---

  - name: Sync - check existing hosts
    shell: cat {{project_dir}}/terraform/{{sync_env_list_item}}.pln.tf | { grep {{sync_hosts_list_item}} || true; }
    register: existing_host_status

  - fail:
      msg: "Host {{sync_hosts_list_item}} is in more than one group in the envoriment {{sync_env_list_item}}."
    when: existing_host_status.stdout != ""

  - name: Sync - insert hosts {{sync_group_list_item}}
    lineinfile:
      path: "{{project_dir}}/terraform/{{sync_env_list_item}}.pln.tf"
      insertafter: '(.*)default(.*)$'
      line: "    {{sync_hosts_list_item}} ={tf_name=\"{{sync_hosts_list_item}}\",}"

  - name: Sync - insert hosts properties {{sync_hosts_list_item}}
    replace:
      path: "{{project_dir}}/terraform/{{sync_env_list_item}}.pln.tf"
      regexp: '(.*{{sync_hosts_list_item}}.*)\}$'
      replace: '\1 {{ item.key }}="{{ item.value }}",}'
    loop: "{{query('dict',(sync_group_list.stdout | from_json)._meta.hostvars[sync_hosts_list_item])}}"
