---

  - name: Start role
    debug:
      msg: "########### INSTALL TERRAFORM WITH VSPHERE PROVIDER ###########"

  - name: Terraform - Create project dir
    file:
      path: "{{project_dir}}/terraform"
      state: directory

  - name: Terraform - Extract terraform binary file
    unarchive:
      src: "{{tf_terraform_archive}}"
      dest: "/usr/bin"
    become: yes
    become_method: sudo
    become_user: root

  - name: Terraform - Create terraform plugins dir
    file:
      path: "~/.terraform.d"
      state: directory

  - name: Terraform - Extract vsphere provider
    unarchive:
      src: "{{tf_provider_archive}}"
      dest: "~/.terraform.d"

  - name: Terraform - Copy project files
    template:
      src: "{{item.srcf}}"
      dest: "{{project_dir}}/terraform/{{item.dstf}}"
    loop:
      - { srcf: 'main.tf.j2', dstf: 'main.tf' }
      - { srcf: 'variables.tf.j2', dstf: 'variables.tf' }
      - { srcf: 'versions.tf', dstf: 'versions.tf' }
      - { srcf: 'output.tf', dstf: 'output.tf' }

  - name: Terraform - Change permisions
    file:
      path: "{{project_dir}}/terraform/variables.tf"
      owner: ansible
      group: root
      mode: '600'
    become: yes

  - name: Terraform - Init project
    shell: cd {{project_dir}}/terraform/ && terraform init -no-color
    register: output
  - debug: var=output.stdout_lines



