---

  - name: Start role
    debug:
      msg: "########### INIT VAULT ###########"

  - name: Vault-init - read root token
    shell: "cat {{project_dir}}/vault/vault-root-token/.access-token"
    register: vault_token
    become: yes

  - name: Vault-init - Wait for building project (take few minutes...)
    uri:
      url: "http://127.0.0.1:8200/v1/sys/health"
      method: GET
      status_code: 200
    register: _result
    until: _result.status == 200
    retries: 60
    delay: 10

  - name: Vault-init - Check if engine exists
    uri:
      url: http://127.0.0.1:8200/v1/sys/mounts
      headers:
        X-Vault-Token: "{{vault_token.stdout}}"
    register: outputjson
    until: outputjson.status == 200
    retries: 10
    delay: 10

  - debug: var=outputjson['json']['{{vault_engine_name}}/']

  - name: Vault-init - check if init-iac.json exist
    stat:
      path: "~/init-iac.json"
    register: status_init_iac

  - set_fact:
      init_iac: "{{ (lookup('file', '~/init-iac.json') | from_json) }}"
    when: status_init_iac.stat.exists

  - name: Vault-init - check if init-cloud.json exist
    stat:
      path: "~/init-cloud.json"
    register: status_init_cloud

  - set_fact:
      init_cloud: "{{ (lookup('file', '~/init-cloud.json') | from_json) }}"
    when: status_init_cloud.stat.exists




  - name: Vault-init - create kv engine with data
    block:

    - name: Vault-engine - create ansible token
      uri:
        url: "http://127.0.0.1:8200/v1/auth/token/create"
        method: POST
        headers:
          X-Vault-Token: "{{vault_token.stdout}}"
        body:
          meta:
            user: "{{ansible_user_id}}"
          renewable: true
        body_format: json
        status_code: 200
      register: vault_response

#    - debug: var=vault_response['json']['auth']['client_token']

    - name: Vault-engine - Create vault config dir
      file:
        path: "/etc/vault"
        state: directory
        mode: '750'
        owner: "{{ansible_user_id}}"
        group: "{{ansible_user_id}}"
      become: yes

    - name: Vault-engine - Copy ansible token to file
      copy:
        dest: "/etc/vault/.vault_ansible_token"
        content: "{{vault_response['json']['auth']['client_token']}}"
        mode: '640'
        owner: "{{ansible_user_id}}"
        group: "{{ansible_user_id}}"
      become: yes

    - name: Vault-engine - Copy ansible engine name to file
      copy:
        dest: "/etc/vault/.vault_engine"
        content: "{{vault_engine_name}}"
        mode: '640'
        owner: "{{ansible_user_id}}"
        group: "{{ansible_user_id}}"
      become: yes

#    - name: Vault - Add path .vault_ansible_token to all.yml
#      lineinfile:
#        path: "../group_vars/all.yml"
#        line: "vault_ansible_token : \"{{vault_ansible_token}}\""
#        create: yes

    - name: Vault-engine - create engine
      uri:
        url: "http://127.0.0.1:8200/v1/sys/mounts/{{vault_engine_name}}"
        method: POST
        headers:
          X-Vault-Token: "{{vault_token.stdout}}"
        body:
          type: kv
          description: "Main storage for ansible secrets"
          config:
            force_no_cache: true
          options:
            version: 1
        body_format: json
        status_code: 204


    - name: Vault-engine - insert init-iac config to vault
      uri:
        url: "http://127.0.0.1:8200/v1/{{vault_engine_name}}/config"
        method: POST
        headers:
          X-Vault-Token: "{{vault_token.stdout}}"
        body: "{{init_iac}}"
        body_format: json
        status_code: 204

    - name: Vault-engine - insert init-cloud config to vault
      uri:
        url: "http://127.0.0.1:8200/v1/{{vault_engine_name}}/cloud"
        method: POST
        headers:
          X-Vault-Token: "{{vault_token.stdout}}"
        body: "{{init_cloud}}"
        body_format: json
        status_code: 204

    when: outputjson['json']['{{vault_engine_name}}/'] is undefined



#  - debug: var=init_iac
