---

  - name: Check if engine exists
    uri:
      url: http://127.0.0.1:8200/v1/sys/mounts
      headers:
        X-Vault-Token: "{{vault_token.stdout}}"
    register: outputjson

  - debug: var=outputjson['json']['{{vault_engine_name}}/']

  - name: Vault - check if init-iac.json exist
    stat:
      path: "/home/ansible/init-iac.json"
    register: status_init_iac

  - set_fact:
      init_iac: "{{ (lookup('file', '/home/ansible/init-iac.json') | from_json) }}"
    when: status_init_iac.stat.exists


  - name: Vault - create kv engine with data
    block:

    - name: Vault-engine - create ansible token
      uri:
        url: "http://127.0.0.1:8200/v1/auth/token/create"
        method: POST
        headers:
          X-Vault-Token: "{{vault_token.stdout}}"
        body:
          meta:
            user: ansible
          renewable: true
        body_format: json
        status_code: 200
      register: vault_response

    - debug: var=vault_response['json']['auth']['client_token']

    - name: Vault - Copy ansible token to file
      copy:
        dest: "{{git_project_dir}}/../.vault_ansible_token"
        content: "{{vault_response['json']['auth']['client_token']}}"
        mode: '600'
        owner: ansible
        group: root
      become: yes

    - name: Vault-engine - create engine
      uri:
        url: "http://127.0.0.1:8200/v1/sys/mounts/{{vault_engine_name}}"
        method: POST
        headers:
          X-Vault-Token: "{{vault_token.stdout}}"
        body:
          type: kv
          description: "Main storage for secrets"
          config:
            force_no_cache: true
          options:
            version: 1
        body_format: json
        status_code: 204


    - name: Vault-engine - insert init-iac config to vault
      uri:
        url: "http://127.0.0.1:8200/v1/{{vault_engine_name}}/config"
        method: POST
        headers:
          X-Vault-Token: "{{vault_token.stdout}}"
        body: "{{init_iac}}"
        body_format: json
        status_code: 204

    when: outputjson['json']['{{vault_engine_name}}/'] is undefined



  - debug: var=init_iac
