---

  - name: Start role
    debug:
      msg: "########### INSTALL PACKER ###########"

  - name: Packer - create project dir
    file:
      path: "{{ project_dir }}"
      state: directory
      mode: '0777'
    become: yes

  - name: Packer - create packer project dir
    file:
      path: "{{ project_dir }}/packer"
      state: directory

  - name: Packer - Extract packer binary file
    unarchive:
      src: "{{tf_packer_archive}}"
      dest: "/usr/bin"
    become: yes

  - name: Packer - copy base projects files
    template:
      src: "{{item.srcf}}"
      dest: "{{project_dir}}/packer/{{item.dstf}}"
    loop:
      - { srcf: 'variables.pkr.hcl.j2', dstf: 'variables.pkr.hcl' }
      - { srcf: 'build.sh', dstf: 'build.sh' }

#  - name: Packer - Create vm template debian
#    include_role:
#      name: 20-crte-packer-template
#    vars:
#      tf_packer_image: "tf-templ-debian11"
#      tf_packer_image_name: "{{tf_packer_debian11_name}}"
#      tf_packer_image_addition_pkgs: "{{tf_packer_debian11_addition_pkgs}}"
#      tf_packer_image_CPUs: "{{tf_packer_debian11_CPUs}}"
#      tf_packer_image_RAM: "{{tf_packer_debian11_RAM}}"
#      tf_packer_image_size: "{{tf_packer_debian11_size}}"
#      tf_packer_image_iso_path: "{{tf_packer_debian11_iso_path}}"
#    when: tf_packer_debian11 == true

#  - name: Packer - Create vm template ubuntu
#    include_role:
#      name: 20-crte-packer-template
#    vars:
#      tf_packer_image: "tf-templ-ubuntu14"
#      tf_packer_image_name: "{{tf_packer_ubuntu14_name}}"
#      tf_packer_image_addition_pkgs: "{{tf_packer_ubuntu14_addition_pkgs}}"
#      tf_packer_image_CPUs: "{{tf_packer_ubuntu14_CPUs}}"
#      tf_packer_image_RAM: "{{tf_packer_ubuntu14_RAM}}"
#      tf_packer_image_size: "{{tf_packer_ubuntu14_size}}"
#      tf_packer_image_iso_path: "{{tf_packer_ubuntu14_iso_path}}"
#    when: tf_packer_ubuntu14 == true


#  - name: Packer - Create vm template debian
#    block:
#      - name: Packer - create template {{tf_packer_debian11_name}}, may take long time
#        shell: cd {{project_dir}}/packer/tf-templ-debian11/ && packer build -force .
#        register: output
#        environment:
#          VAULT_ADDR: "http://127.0.0.1:8200"
#          VAULT_TOKEN: "{{ lookup('file', '/etc/vault/.vault_ansible_token') }}"
#      - debug: var=output.stdout_lines
#    when: tf_packer_debian11 == true

#  - name: Packer - Create vm template ubuntu
#    block:
#      - name: Packer - create template {{tf_packer_ubuntu14_name}}, may take long time
#        shell: cd {{project_dir}}/packer/tf-templ-ubuntu14/ && packer build -force .
#        register: output
#        environment:
#          VAULT_ADDR: "http://127.0.0.1:8200"
#          VAULT_TOKEN: "{{ lookup('file', '/etc/vault/.vault_ansible_token') }}"
#      - debug: var=output.stdout_lines
#    when: tf_packer_ubuntu14 == true




