---

 - hosts: 127.0.0.1
   connection: local

   tasks:

      - name: Create .ssh directory
        file:
          path: /home/ansible/.ssh/
          state: directory

      - name: Generate /home/ansible/.ssh/ RSA host key
        command : ssh-keygen -q -t rsa -b 4096 -f /home/ansible/.ssh/id_rsa -C "" -N ""
        args:
          creates: /home/ansible/.ssh/id_rsa

      - name: Perform a dist-upgrade
        apt:
          upgrade: dist
          update_cache: yes

      - name: Check if a reboot is required
        stat:
          path: /var/run/reboot-required
          get_md5: no
        register: reboot_required_file

      - name: Reboot the server (if required)
        reboot:
        when: reboot_required_file.stat.exists == true

      - name: Remove dependencies that are no longer required
        apt:
          autoremove: yes
