---

 - hosts: 127.0.0.1
   vars_files:
     - "../../init-iac.yml"
   connection: local
   roles:
     - '0-init-host'

# - hosts: vault
#   vars_files:
#     - "../group_vars/all.yml"
#   gather_facts: true
#   roles:
#     - '10-inst-docker'
#     - '10-inst-vault'

 - hosts: 127.0.0.1
   vars_files:
     - "../../init-iac.yml"
     - "../group_vars/all.yml"
   connection: local
   roles:
     - '10-inst-terraform-vsphere'

 - hosts: 127.0.0.1
   vars_files:
     - "../../init-iac.yml"
     - "../group_vars/all.yml"
   gather_facts: true
   connection: local
   roles:
     - '10-inst-docker'
     - '10-inst-gitlab'
